### ISSUE TITLE
Incorrect links generated by \cref

### ISSUE THREAD

**Issue by hanlin-ren** [dagstuhl-publishing/styles#17] opened 2021-05-06 05:39 UTC
Sometimes when I use `\cref` to generate a link to a theorem, the link points to a wrong theorem. For example, I use a `\cref` to refer to Lemma 2.1, and the `\cref` indeed generates the text "Lemma 2.1" in PDF, but when I click this "Lemma 2.1" it points to "Lemma 1.1".

The following is a minimum working example. After I compile it and click the link "Lemma 2.1" (generated by the `\cref`), it points to "Lemma 1.1".

```
\documentclass[a4paper,cleveref, thm-restate, numberwithinsect]{lipics-v2021}
\begin{document}
\section{sec 1}
\begin{lemma}
	sec 1
\end{lemma}

\newpage

\section{sec 2}
\begin{lemma}
	\label{lemma}
	sec 2
\end{lemma}
\cref{lemma}

\end{document}
```

Note that both `numberwithinsect` and `thm-restate` appear necessary. When I remove either of them, everything works perfectly. The bug appears only when I add both `numberwithinsect` and `thm-restate`.

**Comment by hanlin-ren** [comment] 2021-05-06 05:44
Sorry I missed issue #15 which states the same bug...

**Comment by java7mike** [comment] 2021-05-06 05:51
Duplicate of #15

**Closed by java7mike** 2021-05-06 05:51 UTC
