### ISSUE TITLE
Theorem reference issue still exists in lipics-v2021.1.2 (with numberwithinsect+thm-restate)

### ISSUE THREAD

**Issue by nguyentito** [dagstuhl-publishing/styles#27] opened 2023-02-12 12:31 UTC
While writing a paper recently with the latest release of LIPIcs style, I ran into a bug that looks exactly like #15 despite the claim in the changelog that it had been fixed ("fixed problem with numberwithinsect in combination with thm-restate,cleveref, autoref (This fixes #15)").

For the sake of making this issue self-contained, here's a minimal working example (due to @a3nm, who also noticed that the issue persisted in a comment to #15).  In the following example, the second hyperlink points to the first theorem (see [attached pdf](https://github.com/dagstuhl-publishing/styles/files/10716054/mwe.pdf)):
```
\documentclass[numberwithinsect,thm-restate]{lipics-v2021}
\begin{document}
\section{A}
\begin{theorem}
  \label{thm:a}
  foo
  \end{theorem}
  \vfill
  \pagebreak
\section{B}
\begin{theorem}
  \label{thm:b}
  bar
  \end{theorem}
Theorem~\ref{thm:a} and Theorem~\ref{thm:b}.

\end{document}
```

**Comment by java7mike** [comment] 2023-06-13 09:19
Issue seems to be resolved in lipics-v2021.1.3

https://github.com/dagstuhl-publishing/styles/tree/v2021.1.3

Will be tested extensively before the issue is closed here as well.

**Closed** 2023-11-09 15:24 UTC
Labels: bug, help wanted
